name: pyspark_module
description: ''
version: 0.0.1
author: g.ayush@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: pysparkmodule
  parentArtefactID: gayushprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2025-12-17 05:18:15'
pipelines:
  pipelines/p1:
    name: p1
    description: ''
    author: g.ayush@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-12-17 05:18:15'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/p2:
    name: p2_rename
    description: ''
    author: g.ayush@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-12-17 05:18:39'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-12-17 05:18:15'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-12-17T05:18:15.139126Z'
  name: plibMaven
  version: 8.15.1
  id: '1432449078'
  createdAt: '2025-12-17T05:18:15.139126Z'
  type: plibMaven
- modifiedAt: '2025-12-17T05:18:15.139126Z'
  name: plibPypi
  version: 2.1.7
  id: '1448042200'
  createdAt: '2025-12-17T05:18:15.139126Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.53
    isDefault: true
    author: null
    createdAt: '2025-12-17 05:16:20'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.10
    isDefault: true
    author: null
    createdAt: '2025-12-17 05:16:20'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
